server:
  port: 8081

  #database 연동 설정
  spring:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3307/springbasic
      username: castello
      password: 1234
    thymeleaf:
      cache: false
      
  #Spring Data Jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQLInnoDbDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
